name: ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v2

      - name: Setup nuget
        uses: nuget/setup-nuget@v2

      - name: build
        run: script\build.bat

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: XArcade XInput\bin\Release

  deploy:
    needs:
      - build

    runs-on: windows-latest

    steps:
      - name: Download build
        if: endsWith(github.ref, '/master')
        uses: actions/download-artifact@v4
        with:
          name: build
          path: build

      - name: Create archive
        if: endsWith(github.ref, '/master')
        run: |
          7z a xarcade-xinput.zip ".\build\*"

      - name: Release
        if: endsWith(github.ref, '/master')
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: latest
          prerelease: false
          title: Release ${{ github.sha }}
          files: |
            xarcade-xinput.zip
